class Constants:
    MAIN_URL = 'https://qa-scooter.praktikum-services.ru/'
    ORDER_URL = 'https://qa-scooter.praktikum-services.ru/order'
    DZEN_URL = 'https://dzen.ru'
    NAME_FIELD = 'Серж'
    NAME_FIELD_ALT = 'Иоан'
    SURNAME_FIELD = 'Абубу'
    SURNAME_FIELD_ALT = 'Абоба'
    ADDRESS_FIELD = 'Москва, улица Пушкина'
    ADDRESS_FIELD_ALT = 'Москва, дом Колотушкина'
    PHONE_FIELD = '89031111111'
    PHONE_FIELD_ALT = '89042222222'
    СOMMENT = 'Побыстрее'
    COMMENT_ALT = 'Помедленнее'